services:
    huncwot.seemycar.event.listener:
        class: huncwot\seemycar\event\listener
        arguments:
            - '@template'
            - '@huncwot.seemycar.service.main'
        tags:
            - { name: event.listener }

    huncwot.seemycar.service.main:
        class: huncwot\seemycar\service\main
        arguments:
            - '@config'
            - '@profilefields.manager'
