services:
    huncwot.seemycar.cron.task.update_forums:
        class: huncwot\seemycar\cron\task\update_forums
        arguments:
            - '@config'
            - '@huncwot.seemycar.service.main'
        calls:
            - [set_name, [cron.task.seemycar.update_forums]]
        tags:
            - { name: cron.task }

    huncwot.seemycar.event.listener:
        class: huncwot\seemycar\event\listener
        arguments:
            - '@template'
            - '@language'
            - '@huncwot.seemycar.service.main'
        tags:
            - { name: event.listener }

    huncwot.seemycar.service.main:
        class: huncwot\seemycar\service\main
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@profilefields.manager'
